# Generated by Django 3.2.9 on 2021-11-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211120_2311'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='accounts_profile_phone_number_length',
        ),
    ]
