# Generated by Django 3.2.9 on 2021-11-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bra', to='subjects.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='subjects.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gra', to='subjects.grade'),
        ),
    ]
