# Generated by Django 3.2.9 on 2021-11-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
