# Generated by Django 3.2.9 on 2021-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_remove_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
