# Generated by Django 3.2.9 on 2021-11-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_subject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_national_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AlterField(
            model_name='subject',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='subjects.doctor'),
        ),
    ]
