# Generated by Django 3.2.9 on 2021-11-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20211119_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_national_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject_name',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subjects.subject'),
        ),
    ]
