# Generated by Django 3.2.9 on 2021-11-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_lecture_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject_n',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='subjects.subject'),
        ),
    ]
