# Generated by Django 3.2.9 on 2021-11-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20211120_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='subject_n',
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subjects.subject'),
            preserve_default=False,
        ),
    ]
