# Generated by Django 3.2.9 on 2021-11-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20211120_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
    ]
