# Generated by Django 3.2.9 on 2021-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_remove_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_national_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
