# Generated by Django 3.2.9 on 2021-11-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_subject_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='owner',
        ),
    ]
