# Generated by Django 3.2.9 on 2021-11-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_subject_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='lecture_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
