# Generated by Django 3.2.9 on 2021-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_auto_20211121_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
