# Generated by Django 3.2.9 on 2021-11-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_remove_subject_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_national_id',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='doctor_national_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to='subjects.doctor'),
        ),
    ]
