# Generated by Django 3.2.9 on 2021-11-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0024_auto_20211123_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_national_id',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
