# Generated by Django 3.2.9 on 2021-11-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0027_doctor_doctor_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='doctor_national_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='doctor_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
