# Generated by Django 3.2.9 on 2021-11-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0029_remove_doctor_doctor_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
