# Generated by Django 3.2.9 on 2021-11-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0033_auto_20211126_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='subject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subjects.subject'),
        ),
    ]
